# Proper prefix
unbind C-b
set-option -g prefix C-space

# prefix + r  reload configuration
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# status position
# set-option -g status-position top

# mouse on
setw -g mouse on

# set index
set -g base-index 1
setw -g pane-base-index 1

# act like vim
setw -g mode-keys vi
set -g status-keys vi

# select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize pane
bind -r up resizep -U 5 # upward (prefix Ctrl+k)
bind -r down resizep -D 5 # downward (prefix Ctrl+j)
bind -r left resizep -L 5 # to the left (prefix Ctrl+h)
bind -r right resizep -R 5 # to the right (prefix Ctrl+l)

# create new windows/panes in same directory
bind c new-window
bind-key | split-window -hc "#{pane_current_path}"
bind-key - split-window -l30% -vc "#{pane_current_path}"

bind -r H select-window -t :-
bind -r L select-window -t :+

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# theme
source "~/.config/tmux/themes/catppuccin.conf"
