gui:
  showNumstatInFilesView: true
  skipRewordInEditorWarning: true
  tabWidth: 2
  border: single
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 80
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  authorColors:
    "*": blue
  nerdFontsVersion: "3"
  switchTabsWithPanelJumpKeys: true
git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --paging=never
