#!/bin/bash

# focus space
lalt - 1 : /opt/homebrew/bin/rift-cli execute workspace switch 0
lalt - 2 : /opt/homebrew/bin/rift-cli execute workspace switch 1
lalt - 3 : /opt/homebrew/bin/rift-cli execute workspace switch 2
lalt - 4 : /opt/homebrew/bin/rift-cli execute workspace switch 3
lalt - 5 : /opt/homebrew/bin/rift-cli execute workspace switch 4

# move window to space
shift + lalt - 1 : /opt/homebrew/bin/rift-cli execute workspace move-window 0
shift + lalt - 2 : /opt/homebrew/bin/rift-cli execute workspace move-window 1
shift + lalt - 3 : /opt/homebrew/bin/rift-cli execute workspace move-window 2
shift + lalt - 4 : /opt/homebrew/bin/rift-cli execute workspace move-window 3
shift + lalt - 5 : /opt/homebrew/bin/rift-cli execute workspace move-window 4
