#!/bin/bash

theme = light:Rose Pine Dawn,dark:Rose Pine

adjust-cell-height = 45%
font-family = MonoLisa Variable
font-size = 14

background-opacity = 0.90
background-blur = true

confirm-close-surface = false

cursor-style-blink = false
mouse-hide-while-typing = true

macos-option-as-alt = false
macos-titlebar-style = hidden
window-padding-balance = true

# cursor-invert-fg-bg = true
cursor-color=cell-foreground
cursor-text=cell-background
cursor-style = block
mouse-hide-while-typing = true
shell-integration-features = no-cursor

window-padding-x = 6
window-padding-y = 6


title = " "
