return {
  "rose-pine/neovim",
  lazy = false,
  name = "rose-pine",
  config = function()
    require("rose-pine").setup({
      styles = {
        transparency = true,
      },
      highlight_groups = {
        MatchParen = { fg = "love", bg = "love", blend = 25 },
        StatuslineTextMain = { fg = "text", bg = "none" },
        StatuslineTextAccent = { fg = "muted", bg = "none" },
        StatusLineTerm = { link = "StatuslineTextMain" },
        StatuslineModeCommand = { fg = "love", bg = "none", bold = true },
        StatuslineModeInsert = { fg = "foam", bg = "none", bold = true },
        StatuslineModeNormal = { fg = "pine", bg = "none", bold = true },
        StatuslineModeOther = { fg = "pine", bg = "none", bold = true },
        StatuslineModeReplace = { fg = "rose", bg = "none", bold = true },
        StatuslineModeVisual = { fg = "iris", bg = "none", bold = true },
        StatuslineFilepath = { fg = "muted", bg = "none", italic = true },
        QuickFixFilename = { fg = "text" },
        IndentLineCurrent = { fg = "muted" },
        EasyDotnetTestRunnerSolution = { fg = "pine" },
        EasyDotnetTestRunnerProject = { fg = "rose" },
        EasyDotnetTestRunnerTest = { fg = "iris" },
        SnacksIndentScope = { fg = "muted" },
        SnacksDashboardSpecial = { fg = "muted", italic = true },
        SnacksDashboardTitle = { fg = "text" },
        SnacksDashboardDesc = { fg = "muted" },
        SnacksDashboardDir = { fg = "muted", italic = true },
        SnacksDashboardFile = { fg = "text" },
        SnacksDashboardFooter = { fg = "text" },
        DartCurrentLabel = { fg = "gold", bg = "overlay", bold = true },
        DartCurrentModified = { fg = "text", bg = "overlay", bold = true },
        DartCurrentLabelModified = { fg = "gold", bg = "overlay", bold = true },
        DartVisibleLabel = { fg = "gold", bg = "surface", bold = true },
        DartVisibleLabelModified = { fg = "gold", bg = "text", bold = true },
        DartMarkedCurrentLabel = { fg = "gold", bg = "overlay", bold = true },
        DartMarkedCurrentModified = { fg = "text", bg = "overlay", bold = true },
        DartMarkedCurrentLabelModified = { fg = "gold", bg = "overlay", bold = true },
        DartMarkedLabel = { fg = "gold", bg = "surface", bold = true },
        DartMarkedLabelModified = { fg = "gold", bg = "text", bold = true },
        DartPickLabel = { fg = "gold", bg = "none", bold = true },
        WilderText = { fg = "text", bg = "none" },
        WilderMauve = { fg = "foam", bg = "none" },
        WilderAccent = { fg = "gold", bg = "none" },
        SidekickDiffAdd = { fg = "foam", bg = "foam", blend = 25 },
        SidekickDiffDelete = { fg = "love", bg = "love", blend = 25 },
        SidekickDiffContext = { fg = "muted", bg = "none" },
        RenderMarkdownCode = { bg = "overlay" },
        RenderMarkdownCodeInline = { fg = "text", bg = "surface" },
      },
    })
    vim.cmd("colorscheme rose-pine")
  end,
}
