# User paths
fish_add_path "$HOME/.dotfiles"
fish_add_path "$HOME/.local/bin"
fish_add_path "$HOME/.local/scripts"
fish_add_path "$HOME/.opencode/bin"
fish_add_path "$HOME/.config/opencode/scripts"
fish_add_path "$HOME/.bun/bin"
fish_add_path "$HOME/.spicetify"
fish_add_path "$HOME/.dotnet/tools"
fish_add_path "$HOME/.aspire/bin"
fish_add_path "/Applications/Ghostty.app/Contents/MacOS"
