[settings]
idiomatic_version_file_enable_tools = ["dotnet"]

[settings.ruby]

[settings.dotnet]
isolated = false

[tools]
bun = "latest"
dotnet = ["10", "9", "8"]
go = "latest"
node = "latest"
python = "latest"
shfmt = "latest"
stylua = "latest"
biome = "latest"
oxfmt = "latest"
oxlint = "latest"
"cargo:emmylua_ls" = "0.23.2"
"npm:@fsouza/prettierd" = "latest"
"pipx:xmlformatter" = "latest"
"npm:@github/copilot-language-server" = "1.508.0"
"npm:@tailwindcss/language-server" = "0.14.29"
"npm:@vtsls/language-server" = "0.3.0"
