[settings]
idiomatic_version_file_enable_tools = ["dotnet"]

[settings.ruby]

[settings.dotnet]
isolated = false

[tools]
bun = "latest"
dotnet = ["10", "9", "8"]
go = "latest"
gum = "latest"
marksman = "2026-02-08"
node = "latest"
python = "latest"
shfmt = "latest"
stylua = "latest"
biome = "latest"
oxfmt = "latest"
oxlint = "latest"
taplo = "0.10.0"
"cargo:emmylua_ls" = "0.23.2"
"go:golang.org/x/tools/gopls" = "0.22.0"
"npm:@fsouza/prettierd" = "latest"
"npm:bash-language-server" = "5.6.0"
"pipx:xmlformatter" = "latest"
"npm:@github/copilot-language-server" = "1.508.0"
"npm:svelte-language-server" = "0.18.2"
"npm:@tailwindcss/language-server" = "0.14.29"
"npm:@vtsls/language-server" = "0.3.0"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.23.0"
