[settings]
idiomatic_version_file_enable_tools = ["dotnet"]

[settings.ruby]

[settings.dotnet]
isolated = false

[tools]
bun = "latest"
dotnet = ["10", "9", "8"]
go = "latest"
gum = "latest"
node = "latest"
python = "latest"
rust = "latest"
shfmt = "latest"
stylua = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"pipx:xmlformatter" = "latest"
